language: java
script: mvn -B -P ${MAVEN_PROFILE} test verify
env:
  - MAVEN_PROFILE=openjpa
  - MAVEN_PROFILE=eclipselink
  - MAVEN_PROFILE=hibernate42
  - MAVEN_PROFILE=hibernate43
jdk:
  - oraclejdk7
  - oraclejdk8
