language: java
install: mvn -Dskip.unit.tests=true -Dskip.integration.tests=true -P ${MAVEN_PROFILE} -B -V help:active-profiles clean install
script: mvn -B -P ${MAVEN_PROFILE} help:active-profiles test verify
matrix:
  include:
    - jdk: oraclejdk7
      env: MAVEN_PROFILE=jacoco,openjpa
    - jdk: oraclejdk7
      env: MAVEN_PROFILE=jacoco,eclipselink
    - jdk: oraclejdk7
      env: MAVEN_PROFILE=jacoco,hibernate42
    - jdk: oraclejdk7
      env: MAVEN_PROFILE=jacoco,hibernate43
    - jdk: oraclejdk8
      env: MAVEN_PROFILE=openjpa
    - jdk: oraclejdk8
      env: MAVEN_PROFILE=eclipselink
    - jdk: oraclejdk8
      env: MAVEN_PROFILE=hibernate42
    - jdk: oraclejdk8
      env: MAVEN_PROFILE=hibernate43
