language: java
install: mvn -Dskip.unit.tests=true -Dskip.integration.tests=true -P ${MAVEN_PROFILE} -B -V help:active-profiles clean install
script: mvn -B -P ${MAVEN_PROFILE} help:active-profiles test verify
env:
  - MAVEN_PROFILE=openjpa
  - MAVEN_PROFILE=eclipselink
  - MAVEN_PROFILE=hibernate42
  - MAVEN_PROFILE=hibernate43
  - MAVEN_PROFILE=openshift
jdk:
  - oraclejdk7
  - oraclejdk8
